FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache openssl libc6-compat
COPY package*.json ./
RUN npm ci
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm run prisma:generate
EXPOSE 3000
CMD ["sh", "-c", "npm run prisma:generate && npm run start:dev"]
